version: '3.9'

services:
  backendproject:
    build: ./backendproject
    volumes:
      - ./backendproject:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: python manage.py runserver 0.0.0.0:8000

  frontendapp:
    build: ./frontendapp
    ports:
      - "3000:3000"
    container_name: react-frontend
    restart: always








