# Generated by Django 5.2.4 on 2025-08-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialno', models.IntegerField()),
                ('version', models.IntegerField(blank=True, null=True)),
                ('account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('instance_id', models.CharField(blank=True, max_length=100, null=True)),
                ('srcaddr', models.GenericIPAddressField()),
                ('dstaddr', models.GenericIPAddressField()),
                ('srcport', models.IntegerField(blank=True, null=True)),
                ('dstport', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=20, null=True)),
                ('packets', models.IntegerField(blank=True, null=True)),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('starttime', models.BigIntegerField()),
                ('endtime', models.BigIntegerField()),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
                ('log_status', models.CharField(blank=True, max_length=20, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
